export const LOAN_REPOSITORY = 'LOAN_REPOSITORY';
export const MESSAGE_QUEUE = 'MESSAGE_QUEUE';
export const GEOCODING_SERVICE = 'GEOCODING_SERVICE';
export const CREDIT_SCORE_SERVICE = 'CREDIT_SCORE_SERVICE';